openapi: 3.0.1
info:
  title: olderApi
  description: API Definition of olderApi
  version: 1.0.0
servers:
- url: http://localhost:8290/olderapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
